### ISSUE TITLE
greenhouse crash on chart dialog

### ISSUE THREAD

**Issue by perihanmirkelam** [IoT-Ignite/IgniteGreenhouse#5]
09-20 10:52:13.079 27276-27276/? E/AndroidRuntime: FATAL EXCEPTION:main     
                                             
 Process: com.ardic.android.iotignite.greenhouse, PID: 27276                                                   java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List com.ardic.android.iotignite.lib.restclient.model.ThingDataHistory.getList()' on a null object reference                                                       at com.ardic.android.iotignite.greenhouse.DialogChart$2.onDataHistoryTaskComplete(DialogChart.java:98)                                                       at com.ardic.android.iotignite.greenhouse.controllers.ThingDataHistoryController.onPostExecute(ThingDataHistoryController.java:69)                                                       at com.ardic.android.iotignite.greenhouse.controllers.ThingDataHistoryController.onPostExecute(ThingDataHistoryController.java:16)                                                       at android.os.AsyncTask.finish(AsyncTask.java:660)                                                       at android.os.AsyncTask.-wrap1(AsyncTask.java)                                                       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:677)                                                       at android.os.Handler.dispatchMessage(Handler.java:102)                                                       at android.os.Looper.loop(Looper.java:154)                                                       at android.app.ActivityThread.main(ActivityThread.java:6692)                                                       at java.lang.reflect.Method.invoke(Native Method)                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)

**Comment by IoT-Ignite** [comment]
Fixed on [v.1.0.1](https://github.com/IoT-Ignite/IgniteGreenhouse/releases/tag/v1.0.1)
